# Generated by Django 5.2.4 on 2025-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
        model_name='post',
        name='slug',
        field=models.SlugField(max_length=255, null=True, blank=True),
        ),
    ]
